# MSS Server Configuration
# SSH servers for MML command execution

SERVERS:
  MSSTB4:
    ip: 172.29.108.42
    user: AUTOMA
    password: AUTOMA-1

  MSSTB5:
    ip: 172.29.108.106
    user: AUTOMA
    password: AUTOMA-1


ANRITSU:
  ANRITSU_SERVER_IP: "172.29.90.102"
  ANRITSU_SERVER_USERNAME: "pacomat"
  ANRITSU_SERVER_PASSWORD: "Anritsu2025!"